"""

Revision ID: 8c52c83735ba
Revises: 001_initial
Create Date: 2026-01-31 18:10:38.365410+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c52c83735ba'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parents', 'whatsapp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('parents', 'in_coop',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tutors', 'whatsapp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tutors', 'verification_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'''pending'''::character varying"))
    op.create_index(op.f('ix_users_location'), 'users', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_location'), table_name='users')
    op.alter_column('tutors', 'verification_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'''pending'''::character varying"))
    op.alter_column('tutors', 'whatsapp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('parents', 'in_coop',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('parents', 'whatsapp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
